In [20]:
import pandas as pd

In [1]:
from torch import nn, randn
from torch.nn import functional as F
import torch

In [30]:
a = randn(3,4,5)

In [37]:
_a = a[0,0:1,:].clone()
_a

tensor([[-1.3815, -1.0366, -1.3495, -0.5189,  1.0410]])

In [38]:
_a[:] = 0
_a

tensor([[0., 0., 0., 0., 0.]])

In [41]:
torch.cat([a[0, :, :], _a])

tensor([[-1.3815, -1.0366, -1.3495, -0.5189,  1.0410],
        [ 0.1712,  0.9659, -0.5855,  0.5205,  0.0140],
        [ 0.3370,  0.0251, -0.0851, -0.2133, -0.1134],
        [-1.4340, -0.6931,  0.0771, -1.6478, -0.3585],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

In [43]:
a = randn(3,4,5)

In [46]:
_a = a[:,:,:].clone()
_a

tensor([[[ 0.7309, -0.6428, -0.6636,  0.9112, -1.8284],
         [ 0.8880,  2.5412,  0.5708,  0.4459, -2.1536],
         [ 0.4171,  0.3803,  0.3556, -0.6383,  0.1007],
         [ 0.6908,  0.5263,  0.9655, -0.2302,  0.3648]],

        [[ 0.2487,  0.3852,  0.1683, -0.3558,  1.5143],
         [-0.9058,  0.2830,  0.8163,  0.3340, -0.3418],
         [ 0.4614,  1.9832,  0.3731, -1.6793,  1.9163],
         [ 1.4766,  0.0780, -0.2949, -1.0389, -0.6695]],

        [[ 0.2411, -0.4856,  0.2018, -0.2083,  1.3914],
         [ 0.4958, -0.7759, -0.7232,  1.0123, -0.4709],
         [-0.2372,  0.4829,  1.8572, -2.7888,  1.5076],
         [-0.7266,  0.2925,  1.1517, -0.8410,  1.5142]]])

In [ ]:
_a[:] = 0
_a

tensor([[0., 0., 0., 0., 0.]])

In [ ]:
torch.cat([a[0, :, :], _a])

tensor([[-1.3815, -1.0366, -1.3495, -0.5189,  1.0410],
        [ 0.1712,  0.9659, -0.5855,  0.5205,  0.0140],
        [ 0.3370,  0.0251, -0.0851, -0.2133, -0.1134],
        [-1.4340, -0.6931,  0.0771, -1.6478, -0.3585],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

In [98]:
nb_class = 10

In [102]:
a = torch.stack([torch.arange(0,10) for _ in range(2)]).float()

In [103]:
a

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [105]:
def one_hot(T, nb_class, batch_first=True):
    assert len(T.unique()) <= nb_class, "nb_class should be higher then number of unique element in tensor T"
    T_dtype = T.dtype
    if not batch_first: T = T.unsqueeze(0)
    base_tensor = torch.zeros(T.shape[1])
    out = []
    for batch in T:
        out.append(torch.stack([torch.where(batch == uniq, 1, 0) for uniq in range(nb_class)]).T)
    out = torch.stack(out)
    if not batch_first: out = out[0]
    return out.to(T_dtype)
one_hot(a, nb_class, True)

tensor([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],

        [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0.,

In [21]:
import sys

In [28]:
a = randn(30,30,30)

In [29]:
sys.getsizeof(a)

72

In [27]:
with open("./data/processed_data/0.torch", "rb") as f: a = torch.load(f)

In [24]:
with open("./test.torch", "wb") as f: torch.save((randn(3,3), randn(3,3)), f)

In [18]:
torch.cat([torch.tensor([]), randn(1,3,3)])

tensor([[[ 0.5336, -1.5367, -0.1316],
         [-0.1441, -0.5781,  0.2368],
         [ 0.4289, -1.7501,  0.3528]]])

In [7]:
a = randn(60000, 807, 63)

In [93]:
a = randn(3,3)

In [117]:
a = torch.tensor([1,2,3,5])

In [116]:
a = torch.randint(0,61, (16,807))
a

tensor([[ 4, 53, 38,  ..., 40, 60, 14],
        [35, 28, 30,  ...,  6, 57, 34],
        [18, 60, 11,  ..., 41, 37, 55],
        ...,
        [39, 24, 17,  ..., 38, 12, 38],
        [23,  2, 40,  ..., 18, 36, 51],
        [ 8, 41, 20,  ..., 39, 12, 12]])

In [ ]:
nn.Embedding(62, )

In [119]:
F.one_hot(a, 10)

tensor([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [ ]:
torch.randint

In [110]:
y = torch.randint(0,61,(16,10,))
y = F.pad(y, (1,0,0,0), "constant", 0)
y = F.pad(y, (0,807,0,0), "constant", 155)

In [114]:
y[torch.where(y == 155, 0, 1).bool()]

tensor([ 0, 35, 21, 36, 10,  9,  2, 28, 29,  8, 26,  0, 36, 15, 17, 29, 52,  9,
         0, 57, 15, 42,  0,  6, 33, 28, 34, 19, 34, 43, 20, 55,  7,  0, 32, 30,
        50, 47, 30, 43, 32, 47, 48, 19,  0, 30, 56, 15, 21, 53, 28, 44, 43, 31,
        54,  0, 48, 48, 11, 29,  2, 33, 18, 42,  6, 39,  0, 31, 45, 43,  5, 49,
        20, 46, 33,  8,  2,  0,  4, 26, 47, 47, 55,  4, 45, 45, 25, 58,  0, 17,
        60, 20, 33, 34, 35, 60, 11, 34,  1,  0, 33,  5, 48, 16, 31, 31, 12, 38,
        30, 23,  0, 10, 38, 41,  0, 14, 25, 58, 34,  8, 21,  0, 31,  2,  6, 46,
        60, 26, 51, 56, 31, 21,  0,  7, 34,  1, 54, 47, 26, 10, 24, 43, 21,  0,
        46, 18, 25, 23, 28, 40, 37, 49, 32, 49,  0, 19, 43, 60, 23, 60, 15, 58,
        12, 29,  4,  0, 28, 27, 53, 41,  5, 55, 14, 12, 23, 37])

In [90]:
y = torch.stack([torch.arange(0,8) for _ in range(16)])

In [92]:
F.one_hot(y)

tensor([[[1, 0, 0,  ..., 0, 0, 0],
         [0, 1, 0,  ..., 0, 0, 0],
         [0, 0, 1,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 1, 0, 0],
         [0, 0, 0,  ..., 0, 1, 0],
         [0, 0, 0,  ..., 0, 0, 1]],

        [[1, 0, 0,  ..., 0, 0, 0],
         [0, 1, 0,  ..., 0, 0, 0],
         [0, 0, 1,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 1, 0, 0],
         [0, 0, 0,  ..., 0, 1, 0],
         [0, 0, 0,  ..., 0, 0, 1]],

        [[1, 0, 0,  ..., 0, 0, 0],
         [0, 1, 0,  ..., 0, 0, 0],
         [0, 0, 1,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 1, 0, 0],
         [0, 0, 0,  ..., 0, 1, 0],
         [0, 0, 0,  ..., 0, 0, 1]],

        ...,

        [[1, 0, 0,  ..., 0, 0, 0],
         [0, 1, 0,  ..., 0, 0, 0],
         [0, 0, 1,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 1, 0, 0],
         [0, 0, 0,  ..., 0, 1, 0],
         [0, 0, 0,  ..., 0, 0, 1]],

        [[1, 0, 0,  ..., 0, 0, 0],
         [0, 1, 0,  ..., 0, 0, 0],
         [0,

In [80]:
nn.Embedding(61,256)(y).shape

torch.Size([16, 11, 256])

In [17]:
mha = nn.MultiheadAttention(256, 8, batch_first=True)

In [19]:
x = randn(16,807,256)
attn_mask = randn(8*16,807,807)
mha(x, x, x, attn_mask=attn_mask)[0].shape

torch.Size([16, 807, 256])

In [2]:
class Model(nn.Module):
    
    def __init__(
        self,
        x_shape,
        y_shape,
    ):
        super(Model, self).__init__()

        self.x_shape = x_shape
        self.y_shape = y_shape

        #Embedding
        self.l1 = nn.Linear(self.x_shape[2], 256, False)
        self.l2 = nn.Linear(256, 256, False)
        
        self.pe1 = nn.Parameter(torch.zeros((self.x_shape[1], 256)))
        
        # Encoder
        self.attn1 = nn.MultiheadAttention(256, 64)
        
        self.l4 = nn.Linear(256, 256)
        self.l3 = nn.Linear(256, 256)
        self.l5 = nn.Linear(256, 256)
        self.l6 = nn.Linear(256, 256)
        
        # Decoder
        self.attn2 = nn.MultiheadAttention(256, 64)
        
        self.l7 = nn.Linear(256, 256)
        self.l8 = nn.Linear(256, 256)
        self.l9 = nn.Linear(256, 256)
        self.l10 = nn.Linear(256, 256)
        
        # Classifier
        self.l11 = nn.Linear(256, self.y_shape[2])
        
    def forward(self, x):
        
        #Embedding
        x = self.l1(x)
        x = F.gelu(x)
        x = self.l2(x)
        
        #x = x + self.pe1
        
        # Encoder
        x, _ = self.attn1(x, x, x)
        
        x = self.l3(x)
        x = F.gelu(x)
        x = self.l4(x)
        x = self.l5(x)
        x = F.gelu(x)
        x = self.l6(x)
        
        # Decoder
        x, _ = self.attn2(x, x, x)
        
        x = self.l7(x)
        x = F.gelu(x)
        x = self.l8(x)
        x = self.l9(x)
        x = F.gelu(x)
        x = self.l10(x)
        
        # Classifier
        x = x[:,:self.y_shape[1],:]
        
        x = self.l11(x)
        x = F.softmax(x, 1)
        
        return x

In [3]:
model = Model([1,807,63], [1,43,59])
x = model(randn(1,807,63))
x.shape

torch.Size([1, 43, 59])

In [3]:
model = nn.Transformer()

In [10]:
model(randn(1,64,512), randn(1,64,512))

tensor([[[-1.1646, -0.3673,  2.4507,  ..., -0.6352, -1.0502,  0.4277],
         [-1.1142, -0.4135,  0.3524,  ...,  0.2965, -0.8126, -0.2754],
         [ 1.4338,  1.1891,  0.1754,  ..., -0.5571, -1.0016,  0.5825],
         ...,
         [ 0.5385, -1.5545,  0.1536,  ...,  1.6781, -1.1260, -0.8971],
         [ 1.2013,  0.2258,  0.9249,  ..., -0.3320,  0.1370,  0.2925],
         [ 0.9452,  0.7171,  1.1200,  ...,  0.5412,  0.4270,  0.2423]]],
       grad_fn=<NativeLayerNormBackward0>)